### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by chemgirl97** [MolecularAI/reinvent-hitl#1]
Thank you for your code release.

When executing "adapt-mpo.yml" file, an error occurs in the pip: reinvent-models==0.0.15 part.

**Comment by alexvoronov** [comment]
Thanks! And welcome to MolecularAI! 
Yes, indeed, 0.0.15 is [not on PyPI yet](https://pypi.org/project/reinvent-models/#history), could you please try if `0.0.15rc1` or `0.0.14` would work for you?
